[package]
name = "duplicates"
version = "0.1.0"
authors = ["Jarosław Pawlak <jaroslaw.pawlak@gmail.com>"]
edition = "2018"

[dependencies]
rust-crypto = "^0.2"
walkdir = "2"
rusqlite = "0.21.0"
config = "0.10.1"
serde_derive = "^1.0.8"
serde = "^1.0.8"
notify = "4.0.15"


[dev-dependencies]
counters = "0.5.0"
